---
#-------------------------------
# General Site Settings

title: Doublr Digital
logo:
author: Reda JAIFAR
description: Doublr Digital IT consultancy Company
email: contact@doublr.digital
phone: +33 174 344 512
address: 33 Rue La Fayette, 75009 Paris
copyright: Copyright &copy; 2022 Doublr Digital

menu:
  - { name: About, link: "/about" }
  - { name: Blog, link: "/blog" }
  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: we help design, co-build, and deliver software that drives your next-generation digital transformation

social:
  - { icon: "ti-facebook", link: "#" }
  - { icon: "ti-instagram", link: "#" }
  - { icon: "ti-dribbble", link: "#" }
  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
blurb: design, build, and deliver your next digital systems with a trusted partner that support your business, your vision, and your teams

blurb-btn-link: "/about"
blurb-btn-name: know more

# About Page

# Work Process Section
work-process:
  - title: "Research and Plan"
    icon: "assets/images/icons/plan.png"
    content: "We address 3 pillars: viability for the business, desirability to measure the match between value proposition and user fit, and finally the feasibility"

  - title: "Design and Develop"
    icon: "assets/images/icons/design.png"
    content: "Create UX personas through user interviews and define those early users who will co-build and validate the delivering value"

  - title: "Deliver"
    icon: "assets/images/icons/print.png"
    content: "Using clean code, best practices and adequate architectures to deliver highly robust and effective software"

# My Team Section
team:
  - title: "Reda JAIFAR"
    image: "assets/images/team/member-1.png"
    designation: "Senior Software Engineer"

  - title: "Ghazal Rim"
    image: "assets/images/team/member-2.png"
    designation: "IT Consultant"

  - title: "Abraham Leyth"
    image: "assets/images/team/member-3.png"
    designation: "Designer"

#-------------------------------
# Skills Section

skills-title: Offers
skills:
  - { name: MVP conducting , color: "#fdb157", value: "90%" }
  - { name: Software Development, color: "#9473e6", value: "60%" }
  - { name: Cloud Computing, color: "#bdecf6", value: "80%" }
  - { name: Training, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
  - {
    name: Junior UX Designer,
    icon: "icon-1.png",
    date: "Jan 2007 - Feb 2009",
    organization: "WEBEX",
  }
  - {
    name: UX & UI Designer,
    icon: "icon-2.png",
    date: "Mar 2009 - Aug 2014",
    organization: "AUGMEDIX",
  }
  - {
    name: Senior UI Designer,
    icon: "icon-3.png",
    date: "Sep 2014 - Present",
    organization: "THEMEFISHER",
  }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
    name: Marters in UX Design,
    date: "2006",
    organization: "Masassusets Institute of Technology",
  }
  - {
    name: Honours in Fine Arts,
    date: "2004",
    organization: "Harvard University",
  }
  - {
    name: Higher Secondary Certificat,
    date: "2000",
    organization: "Cardiff School",
  }
  - {
    name: Secondary School Certificate,
    date: "1998",
    organization: "Cardiff School",
  }

#-------------------------------
# Services Section

services-title: Services
services:
  - {
    name: Development,
    icon: ti-layout-slider,
    description: "develop and build reliable software and apps with future-proof technologies that fit your business requirements.",
    active: true # Add true to select section
  }
  - {
    name: UX Design,
    icon: ti-layout-column4-alt,
    description: "Using the latest techniques in UX and UI, we co-create with you and your users a fancy application usage experiences",
    active: true, # Add true to select section
  }
  - {
    name: Integration,
    icon: ti-layout-grid3,
    description: "Let your systems and those of your partners connect and cooperate to deliver highly robust services.",
    active: true # Add true to select section
  }


#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"

  - image: "assets/images/portfolio/item-4.png"
    url: "#"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"

# Portfolio Page
portfolio-label:
  - { title: "UI/UX Design", type: "design" }
  - { title: "BRANDING", type: "branding" }
  - { title: "ILLUSTRATION", type: "illustration" }

portfolio-items:
  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"

  - image: "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"

  - image: "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

  - image: "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"

  - image: "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"

  - image: "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"

  - image: "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"

#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Willy Regonne Grey"
    image: "assets/images/testimonial/client-1.jpeg"
    designation: "Total Energies"
    content: "It has been a real pleasure to work with Reda for many years. He has solid technical bases and knows how to deal with difficulties. This height of view has allowed us to move forward effectively on many application projects at Dassault Systèmes. Finally Reda is an empathetic and benevolent person, which makes him a natural leader!"

  - name: "Vincent Dedeban"
    image: "assets/images/testimonial/client-2.jpeg"
    designation: "GE Healthcare"
    content: "I worked with Reda in GE healthcare. He was part of a scrum team. He managed to take on complex developments on his own. He always tried to understand the reasons for a particular decision. He proactively made suggestions to improve the code, the design, and the processes of the team."

  - name: "Yves Sterbak-Dicke"
    image: "assets/images/testimonial/client-3.jpeg"
    designation: "Protostellar CEO"
    content: "I worked with Reda over 2 years. He is really a smart guy and is very engaged. Was just nice to have him in the team."

  - name: "Zoumana TRAORE"
    image: "assets/images/testimonial/client-4.jpeg"
    designation: "Cloudly Yours CEO"
    content: "I had the pleasure to work with Reda within the same organization. Reda's team was providing technologies used by mine to build services that create values for Dassaut Systèmes PaaS/ Cloud 

Always nice, calm and professionnal to work with even during crisis, Reda was one of the top people i know around looking to stay up to date with leading frameworks, tools and architectures. Very curious and ambitious. 

I recommend him for any 
Software Architect, Lead Dev, Team Lead, Technology Manager and Cloud and app expert roles you may have to provide to a realiable person."

#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-6.png"
    url: "https://www.3ds.com/"

  - logo: "assets/images/clients-logo/client-logo-7.png"
    url: "https://www.gehealthcare.com/"

  - logo: "assets/images/clients-logo/client-logo-8.png"
    url: "https://www.thalesdigital.io/en/"

  - logo: "assets/images/clients-logo/client-logo-9.png"
    url: "https://protostellar.eu/en/start/"

  - logo: "assets/images/clients-logo/client-logo-10.png"
    url: "https://www.cartier.com/"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: contact@doublr.digital
